on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
